(ns kotobase-peer.materialized-view
  "Deprecated compatibility facade for `kotobase.projection`."
  (:require [kotobase.projection :as impl]))

(def format-version impl/format-version)
(def build-bloom impl/build-bloom)
(def bloom-might-contain? impl/bloom-might-contain?)
(def view-key impl/view-key)
(def object-put impl/object-put)
(def object-range-get impl/object-range-get)
(def build-view impl/build-view)
(def build-view-delta impl/build-view-delta)
(def compose-view-segments impl/compose-view-segments)
(def build-datom-projection impl/build-datom-projection)
(def descriptor-pack-cid impl/descriptor-pack-cid)
(def select-blocks impl/select-blocks)
(def coalesce-block-ranges impl/coalesce-block-ranges)
(def range-query-plan impl/range-query-plan)
(def batch-point-query-plan impl/batch-point-query-plan)
(def decode-range impl/decode-range)
(def finish-logical-blocks-rows impl/finish-logical-blocks-rows)
(def finish-logical-blocks-query impl/finish-logical-blocks-query)
(def finish-logical-blocks-batch-query impl/finish-logical-blocks-batch-query)
(def finish-range-rows impl/finish-range-rows)
(def finish-range-query impl/finish-range-query)
(def query-packed impl/query-packed)
(def range-query-plan-chain impl/range-query-plan-chain)
(def finish-range-query-chain impl/finish-range-query-chain)
(def query-packed-chain impl/query-packed-chain)
(def packed-chain-compaction-plan impl/packed-chain-compaction-plan)
(def compact-packed-chain impl/compact-packed-chain)
